name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag (e.g., v1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build all targets (get, vendor, build, test, cross)
        run: |
          make get
          make vendor
          make build
          make test
          make cross

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHASUMS256.txt

      - name: Validate version input (manual dispatch only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          case "${{ github.event.inputs.version }}" in
            v*) ;;
            *) echo "version must start with 'v' (e.g., v1.2.3)" >&2; exit 1;;
          esac

      - name: Create GitHub Release and upload assets
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || '' }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.prerelease || false }}
          generate_release_notes: true
          files: |
            dist/qrc-*
            dist/SHASUMS256.txt
